services:
  app:
    build: .
    image: synesthetic-mcp
    container_name: synesthetic-mcp
    
    environment:
      - SYN_SCHEMAS_DIR
      - SYN_EXAMPLES_DIR
      - SYN_BACKEND_URL
    volumes:
      - .:/app
    command: pytest -q

  serve:
    build: .
    image: synesthetic-mcp
    environment:
      MCP_ENDPOINT: ${MCP_ENDPOINT:-stdio}
      MCP_SOCKET_PATH: ${MCP_SOCKET_PATH:-/tmp/mcp.sock}
      MCP_SOCKET_MODE: ${MCP_SOCKET_MODE:-0600}
      MCP_PORT: ${MCP_PORT:-7000}
      MCP_READY_FILE: /tmp/mcp.ready
      SYN_SCHEMAS_DIR: ${SYN_SCHEMAS_DIR:-}
      SYN_EXAMPLES_DIR: ${SYN_EXAMPLES_DIR:-}
      SYN_BACKEND_URL: ${SYN_BACKEND_URL:-}

    volumes:
      - /tmp:/tmp
    command: ["python", "-m", "mcp"]
    ports:
      - "${MCP_PORT:-7000}:${MCP_PORT:-7000}"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/mcp.ready ]"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
