services:
  app:
    build: .
    image: synesthetic-mcp
    container_name: synesthetic-mcp
    environment:
      - SYN_SCHEMAS_DIR=${SYN_SCHEMAS_DIR:-/app/tests/fixtures/schemas}
      - SYN_EXAMPLES_DIR=${SYN_EXAMPLES_DIR:-/app/tests/fixtures/examples}
      - SYN_BACKEND_URL=${SYN_BACKEND_URL:-}
    volumes:
      - .:/app
    command: pytest -q
