services:
  app:
    build: .
    image: synesthetic-mcp
    container_name: synesthetic-mcp
    # Environment is passed through from host if set; no defaults here
    environment:
      - SYN_SCHEMAS_DIR
      - SYN_EXAMPLES_DIR
      - SYN_BACKEND_URL
    volumes:
      - .:/app
    command: pytest -q
