services:
  app:
    build: .
    image: synesthetic-mcp
    container_name: synesthetic-mcp
    # Environment is passed through from host if set; no defaults here
    environment:
      - SYN_SCHEMAS_DIR
      - SYN_EXAMPLES_DIR
      - SYN_BACKEND_URL
    volumes:
      - .:/app
    command: pytest -q
  serve:
    build: .
    image: synesthetic-mcp
    environment:
      MCP_ENDPOINT: ${MCP_ENDPOINT:-stdio}
      MCP_READY_FILE: ${MCP_READY_FILE:-/tmp/mcp.ready}
      SYN_SCHEMAS_DIR: ${SYN_SCHEMAS_DIR:-}
      SYN_EXAMPLES_DIR: ${SYN_EXAMPLES_DIR:-}
      SYN_BACKEND_URL: ${SYN_BACKEND_URL:-}
    command: ["python", "-m", "mcp"]
    healthcheck:
      test: ["CMD-SHELL", "[ -f ${MCP_READY_FILE:-/tmp/mcp.ready} ]"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
